name: Test
on: [push]

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Python Style Checker
              uses: andymckay/pycodestyle-action@0.1.3

